// Role reading library: DOM text nodes only, including untrusted source excerpts.
const studyArea=document.createElement('section');
studyArea.innerHTML=`<h2>Рабочая библиотека Алины · из книг</h2><p>1. Информационная безопасность → 2. Проектирование → 3. Архитектура систем → 4. Остальные книги. Затем новый круг: только новые и изменённые документы.</p><div class="row"><strong id="study-stage">Подключение очереди…</strong><button id="study-auto">Автоматический порядок</button></div><p id="study-cycle"></p><div id="study-tracks" class="cards"></div><p>«Полностью» означает извлечение текста. Выдержки — материал для разбора, а не доказательство усвоения книги или обучения весов модели.</p><h2 id="study-results-title">Результаты по ИБ</h2><div class="row"><span id="study-result-state"></span><button id="study-retry">Повторить ошибки этого раздела</button></div><div id="study-books"></div>`;
document.querySelector('main').insertBefore(studyArea,document.querySelector('main section'));
const studyStyle=document.createElement('style');studyStyle.textContent='.study-card{padding:15px!important}.study-card h3{font-size:17px;min-height:42px}.study-card strong{font-size:25px}.study-card button{padding:8px;font-size:12px;margin:4px 3px 0 0}.study-note{white-space:pre-wrap;border-left:3px solid #50d2ae;padding:10px 15px;background:#0e1a2b}.study-book{border-bottom:1px solid #30435a;padding:18px 0}.study-book summary{cursor:pointer;overflow-wrap:anywhere}.study-count{line-height:1.8;font-size:13px}';document.head.append(studyStyle);
let selectedStudy='security';
const domainTitles={security:'Информационная безопасность',design:'Проектирование',architecture:'Архитектура систем',other:'Остальная библиотека'};
const states={pending:'В очереди',ready:'Текст извлечён полностью',partial:'Текст извлечён частично',error:'Ошибка',oversize:'Требуется отдельный разбор большого файла'};
async function studyAction(action){const response=await fetch('/api/'+action,{method:'POST',headers:{'X-Alina-Token':token}});if(!response.ok){document.getElementById('study-result-state').textContent='Не удалось выполнить действие. Обновите страницу.';return}await updateStudy();await loadBooks(selectedStudy)}
document.getElementById('study-auto').onclick=()=>studyAction('focus/auto');
document.getElementById('study-retry').onclick=()=>studyAction('retry/'+selectedStudy);
async function loadBooks(domain){selectedStudy=domain;const data=await(await fetch('/api/books?domain='+encodeURIComponent(domain))).json();document.getElementById('study-results-title').textContent='Результаты · '+domainTitles[domain];document.getElementById('study-result-state').textContent='Последние 15 документов; отрывки со ссылкой на исходник';const target=document.getElementById('study-books');target.replaceChildren();for(const book of data.books){const box=document.createElement('details');box.className='study-book';const title=document.createElement('summary');const name=book.path.replaceAll('\\','/').split('/').pop();title.textContent=name+' — '+(states[book.status]||book.status)+' · '+book.chunks+' фрагментов';box.append(title);const meta=document.createElement('p');meta.className='path muted';meta.textContent=book.path+(book.sha?' · SHA-256: '+book.sha:'');box.append(meta);if(book.error){const error=document.createElement('p');error.className='error';error.textContent=book.error;box.append(error)}for(const note of book.notes){const text=document.createElement('div');text.className='study-note';text.textContent=note.locator+'\n'+note.excerpt;box.append(text)}if(!book.notes.length){const note=document.createElement('p');note.textContent='Выдержек пока нет.';box.append(note)}target.append(box)}if(!data.books.length){const note=document.createElement('p');note.textContent='В этом разделе ещё нет поддерживаемых книг в учёте.';target.append(note)}if(data.unsupported.length){const h=document.createElement('h3');h.textContent='Нужен дополнительный обработчик формата';target.append(h);for(const path of data.unsupported){const p=document.createElement('p');p.className='path muted';p.textContent=path;target.append(p)}}}
async function updateStudy(){try{const status=await(await fetch('/api/status')).json();const s=status.study;if(!s)return;document.getElementById('study-stage').textContent='Сейчас: '+(status.live.study_domain||'подготовка очереди')+(status.live.source_kind==='book'?' · книга':'');document.getElementById('study-cycle').textContent=`Круг ${s.cycle} · ${s.cycle_state==='waiting'?'ожидание новых материалов':'очередь активна'} · обходов каталогов: ${s.scans} · приоритет: ${domainTitles[s.focus]||'автоматический'}`;const root=document.getElementById('study-tracks');root.replaceChildren();for(const track of s.tracks){const box=document.createElement('div');box.className='card study-card';let title=document.createElement('h3');title.textContent=track.title;let count=document.createElement('strong');count.textContent=track.ready+' / '+track.books;let small=document.createElement('div');small.className='study-count';small.textContent=`Полностью / найдено файлов книг · ${track.progress}%`;let bar=document.createElement('progress');bar.max=100;bar.value=track.progress;let detail=document.createElement('p');detail.className='study-count';detail.textContent=`В очереди: ${track.pending} · Требуют внимания: ${track.attention}\nФрагментов: ${track.chunks} · Выдержек: ${track.notes}\nСправочных документов: ${track.references}`;detail.style.whiteSpace='pre-line';let view=document.createElement('button');view.textContent='Посмотреть результат';view.onclick=()=>loadBooks(track.id);let focus=document.createElement('button');focus.textContent='В приоритет';focus.onclick=()=>studyAction('focus/'+track.id);box.append(title,count,small,bar,detail,view,focus);root.append(box)}}catch(e){document.getElementById('study-stage').textContent='Обновление фонового процесса…'}}
updateStudy();loadBooks(selectedStudy).catch(()=>{});setInterval(updateStudy,12000);
